/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagementsystem;

import static hotelmanagementsystem.Fieldsdata.autocapitalizefirstletter;
import static hotelmanagementsystem.Fieldsdata.onlyint;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author User
 */
public class AddEmployee extends javax.swing.JPanel {

    public char[] Pa;
    public String ID;
    public String date;

    Connection conn = new DBconnect().connect();
    Statement stmt = null;

    /**
     * Creates new form AddNewUser
     */
    public AddEmployee() {
        initComponents();

        load();

    }

    private void load() {
        //Add Departments to Combobox
        position1.removeAllItems();
        position1.addItem("Select Department");
        position1.addItem("Manager");
        position1.addItem("Hotel Manager");
        position1.addItem("Housekeeping");

        //Add autogenerated ID
        id.setVisible(false);
        idd.setVisible(false);
        //Place Current Date 
        date = DateTime.getTodayDate();
        dat.setText(date);

        //reset all fields
        fname.setText("First");
        lname.setText("Last");
        street1.setText("Street");
        city1.setText("City");
        prov1.setText("Province");
        pc1.setText("PC");
        phone1.setText("");
        email1.setText("");
        user.setText("");
        pas.setText("");

    }

    private void GetDatathenCheckandWrite() {
        //Get DATA from fields
        String email = email1.getText();
        Email useremail = new Email(email);
        String valid = useremail.validateEmailAddress();
        String firstname = fname.getText();
        String lastname = lname.getText();
        String phone = phone1.getText();
        String street = street1.getText();
        String city = city1.getText();
        String prov = prov1.getText();
        String pc = pc1.getText();
        String username = user.getText();
        String department = "" + position1.getSelectedItem();
        Pa = pas.getPassword();
        String Password = "";
        System.out.println(Password);
        for (int i = 0; i < Pa.length; i++) {
            Password += Pa[i];
        }
        // String data = ID + "," + firstname + "," + lastname + "," + department + "," + salary + "," + phone + "," + email + "," + username + "," + Password;

        //Check Validity
        if (firstname.equals("") || firstname.equals("First")) {
            JOptionPane.showMessageDialog(null, "First name is required");
        }
        if (lastname.equals("") || lastname.equals("Last")) {
            JOptionPane.showMessageDialog(null, "Last name is required");
        } else if (department.equals("Select Department")) {
            JOptionPane.showMessageDialog(null, "Department needs to be selected");
        } else if (phone.equals("")) {
            JOptionPane.showMessageDialog(null, "Phone no. is required");
        } else if (street.equals("") || street.equals("Street")) {
            JOptionPane.showMessageDialog(null, "Street is required");
        } else if (city.equals("") || city.equals("City")) {
            JOptionPane.showMessageDialog(null, "City is required");
        } else if (prov.equals("") || prov.equals("Province")) {
            JOptionPane.showMessageDialog(null, "Province is required");
        } else if (pc.equals("") || pc.equals("Postal Code")) {
            JOptionPane.showMessageDialog(null, "Postal Code is required");
        } else if (valid.equals("Invalid Email Address")) {
            JOptionPane.showMessageDialog(null, valid);
        } else if (username.equals("")) {
            JOptionPane.showMessageDialog(null, "Username is required");
        } else if (Password.equals("")) {
            JOptionPane.showMessageDialog(null, "Password is required");
        } else {

            //Write
            //WriteToFile("userfile.txt", "userID.txt", data, ID);

            //Reload Panel
            load();

        }

    }

    private void GetDatathenCheckandWriteDatabase() {
        //Get DATA from fields
        String email = email1.getText();
        Email useremail = new Email(email);
        String valid = useremail.validateEmailAddress();
        String firstname = fname.getText();
        String lastname = lname.getText();
        String phone = phone1.getText();
        String street = street1.getText();
        String city = city1.getText();
        String prov = prov1.getText();
        String pc = pc1.getText();
        String username = user.getText();
        String department = "" + position1.getSelectedItem();
        Pa = pas.getPassword();
        String Password = "";
        System.out.println(Password);
        for (int i = 0; i < Pa.length; i++) {
            Password += Pa[i];
        }
        // String data = ID + "," + firstname + "," + lastname + "," + department + "," + salary + "," + phone + "," + email + "," + username + "," + Password;

        //Check Validity
        if (firstname.equals("") || firstname.equals("First")) {
            JOptionPane.showMessageDialog(null, "First name is required");
        }
        if (lastname.equals("") || lastname.equals("Last")) {
            JOptionPane.showMessageDialog(null, "Last name is required");
        } else if (department.equals("Select Department")) {
            JOptionPane.showMessageDialog(null, "Department needs to be selected");
        } else if (phone.equals("")) {
            JOptionPane.showMessageDialog(null, "Phone no. is required");
        } else if (street.equals("") || street.equals("Street")) {
            JOptionPane.showMessageDialog(null, "Street is required");
        } else if (city.equals("") || city.equals("City")) {
            JOptionPane.showMessageDialog(null, "City is required");
        } else if (prov.equals("") || prov.equals("Province")) {
            JOptionPane.showMessageDialog(null, "Province is required");
        } else if (pc.equals("") || pc.equals("Postal Code")) {
            JOptionPane.showMessageDialog(null, "Postal Code is required");
        } else if (valid.equals("Invalid Email Address")) {
            JOptionPane.showMessageDialog(null, valid);
        } else if (username.equals("")) {
            JOptionPane.showMessageDialog(null, "Username is required");
        } else if (Password.equals("")) {
            JOptionPane.showMessageDialog(null, "Password is required");
        } else {
            //Write
            try {
                PreparedStatement pa = conn.prepareStatement("insert into Employee(First_Name,Last_Name,Department,Street,City,Province,PC,Phone,Email,Username,Password) values (?,?,?,?,?,?,?,?,?,?,?)");

                pa.setString(1, firstname);
                pa.setString(2, lastname);
                pa.setString(3, department);
                pa.setString(4, street);
                pa.setString(5, city);
                pa.setString(6, prov);
                pa.setString(7, pc);
                pa.setString(8, phone);
                pa.setString(9, email);
                pa.setString(10, username);
                pa.setString(11, Password);

                int i = pa.executeUpdate();

                if (i > 0) {
                    JOptionPane.showMessageDialog((null), "saved");
                } else {
                    JOptionPane.showMessageDialog((null), "notsaved");

                }
            } catch (SQLException se) {
                //Handle errors for JDBC
                se.printStackTrace();
            } catch (Exception e) {
                //Handle errors for Class.forName
                e.printStackTrace();
            }
            //Reload Panel
            load();

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        position1 = new javax.swing.JComboBox();
        save = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        idd = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        phone1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        email1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        street1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        dat = new javax.swing.JLabel();
        pas = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        prov1 = new javax.swing.JTextField();
        city1 = new javax.swing.JTextField();
        pc1 = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Add User");

        jLabel2.setText("Name");

        fname.setText("First");
        fname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fnameFocusLost(evt);
            }
        });
        fname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fnameMouseClicked(evt);
            }
        });

        jLabel4.setText("Position");

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        id.setText("Autogenerated");

        idd.setText("ID");

        lname.setText("Last");
        lname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lnameFocusLost(evt);
            }
        });
        lname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lnameMouseClicked(evt);
            }
        });

        phone1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phone1KeyTyped(evt);
            }
        });

        jLabel7.setText("Phone No.");

        jLabel8.setText("Email Address");

        jLabel9.setText("Username");

        jLabel10.setText("Password");

        street1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                street1MouseClicked(evt);
            }
        });
        street1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                street1KeyTyped(evt);
            }
        });

        jLabel11.setText("Address");

        dat.setText("Current Date");

        prov1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prov1MouseClicked(evt);
            }
        });
        prov1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prov1KeyTyped(evt);
            }
        });

        city1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                city1MouseClicked(evt);
            }
        });
        city1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                city1KeyTyped(evt);
            }
        });

        pc1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pc1MouseClicked(evt);
            }
        });
        pc1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pc1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(dat, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(555, 555, 555)
                .addComponent(jLabel3))
            .addGroup(layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(idd)
                .addGap(18, 18, 18)
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(526, 526, 526)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(461, 461, 461)
                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel11)
                    .addComponent(jLabel7))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(street1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(position1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(city1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prov1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pc1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(phone1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(176, 176, 176)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pas, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dat)
                .addGap(83, 83, 83)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idd))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(position1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(street1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel9))
                                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(pas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(city1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prov1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(phone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(email1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 192, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        GetDatathenCheckandWriteDatabase();

    }//GEN-LAST:event_saveActionPerformed

    private void phone1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phone1KeyTyped
        onlyint(evt);
    }//GEN-LAST:event_phone1KeyTyped

    private void fnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnameFocusLost
        autocapitalizefirstletter(fname);
    }//GEN-LAST:event_fnameFocusLost

    private void lnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lnameFocusLost
        autocapitalizefirstletter(lname);
    }//GEN-LAST:event_lnameFocusLost

    private void fnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fnameMouseClicked
        String firstname = fname.getText();
        if (firstname.equals("First")) {
            fname.setText("");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_fnameMouseClicked

    private void lnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lnameMouseClicked
        String lastname = lname.getText();
        if (lastname.equals("Last")) {
            lname.setText("");
        }         // TODO add your handling code here:
    }//GEN-LAST:event_lnameMouseClicked

    private void street1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_street1KeyTyped
            // TODO add your handling code here:
    }//GEN-LAST:event_street1KeyTyped

    private void prov1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prov1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_prov1KeyTyped

    private void city1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_city1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_city1KeyTyped

    private void pc1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pc1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_pc1KeyTyped

    private void street1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_street1MouseClicked
      String street = street1.getText();
        if (street.equals("Street")) {
            street1.setText("");
        }     // TODO add your handling code here:
    }//GEN-LAST:event_street1MouseClicked

    private void city1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_city1MouseClicked
     String city = city1.getText();
        if (city.equals("City")) {
            city1.setText("");
        }   // TODO add your handling code here:
    }//GEN-LAST:event_city1MouseClicked

    private void prov1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prov1MouseClicked
     String prov = prov1.getText();
        if (prov.equals("City")) {
            prov1.setText("");
        }    // TODO add your handling code here:
    }//GEN-LAST:event_prov1MouseClicked

    private void pc1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pc1MouseClicked
    String pc = pc1.getText();
        if (pc.equals("City")) {
            pc1.setText("");
        }     // TODO add your handling code here:
    }//GEN-LAST:event_pc1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField city1;
    private javax.swing.JLabel dat;
    private javax.swing.JTextField email1;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField id;
    private javax.swing.JLabel idd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lname;
    private javax.swing.JPasswordField pas;
    private javax.swing.JTextField pc1;
    private javax.swing.JTextField phone1;
    private javax.swing.JComboBox position1;
    private javax.swing.JTextField prov1;
    private javax.swing.JButton save;
    private javax.swing.JTextField street1;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
